In [6]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
%matplotlib inline

DD = np.array([[2.00,0.00,0.00,0,0,0],[0,3,0,0,0,0]
               ,[0,0,2,0,0,0],[0,0,0,3,0,0]
               ,[0,0,0,0,3,0],[0,0,0,0,0,1]])

In [7]:
DD

array([[2., 0., 0., 0., 0., 0.],
       [0., 3., 0., 0., 0., 0.],
       [0., 0., 2., 0., 0., 0.],
       [0., 0., 0., 3., 0., 0.],
       [0., 0., 0., 0., 3., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [8]:
AA = np.array([[0.00,1.00,0.00,0.00,1.00,0.00]
                 ,[1.00,0.00,1.00,0.00,1.00,0.00]
               ,[0.00,1.00,0.00,1.00,0.00,0.00]
                 ,[0.00,0.00,1.00,0.00,1.00,1.00]
               ,[1.00,1.00,0.00,1.00,0.00,0.00]
                 ,[0.00,0.00,0.00,1.00,0.00,0.00]])

In [9]:
AA

array([[0., 1., 0., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 0.],
       [0., 0., 1., 0., 1., 1.],
       [1., 1., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0.]])

In [10]:
LL = DD -AA

In [11]:
LL

array([[ 2., -1.,  0.,  0., -1.,  0.],
       [-1.,  3., -1.,  0., -1.,  0.],
       [ 0., -1.,  2., -1.,  0.,  0.],
       [ 0.,  0., -1.,  3., -1., -1.],
       [-1., -1.,  0., -1.,  3.,  0.],
       [ 0.,  0.,  0., -1.,  0.,  1.]])

In [12]:
invDD = np.linalg.inv(DD)

In [13]:
invDD

array([[0.5       , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.33333333, 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.5       , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.33333333, 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.33333333,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        1.        ]])

In [14]:
L_rw = np.matmul(invDD,LL)

In [15]:
L_rw

array([[ 1.        , -0.5       ,  0.        ,  0.        , -0.5       ,
         0.        ],
       [-0.33333333,  1.        , -0.33333333,  0.        , -0.33333333,
         0.        ],
       [ 0.        , -0.5       ,  1.        , -0.5       ,  0.        ,
         0.        ],
       [ 0.        ,  0.        , -0.33333333,  1.        , -0.33333333,
        -0.33333333],
       [-0.33333333, -0.33333333,  0.        , -0.33333333,  1.        ,
         0.        ],
       [ 0.        ,  0.        ,  0.        , -1.        ,  0.        ,
         1.        ]])

在Python中可以使用NumPy中的sum函数来进行数值求和，sum方法的格式如下：

numpy.sum(a, axis=None, dtype=None, out=None, keepdims=, initial=)

常用参数含义如下：

a - 待求和的数组；

axis - 求和的方向，None或没有axis参数表示全部数据相加，axis=0，表示按列相加，axis=1，表示按行相加，对于一维数组，只有axis=0，表示按行相加，没有axis=1，输入axis=1会报错；

dtype - 输出结果数据的数据类型。

示例代码：

>>> import numpy as np  
>>> A=np.array([[1,2],[3,4],[5,6]])  
>>> np.sum(A)  
21  
>>> np.sum(A,axis=0)  
array([ 9, 12])  
>>> np.sum(A,axis=1)  
array([ 3,  7, 11])  

In [16]:
np.sum(L_rw,axis=0) 

array([ 0.33333333, -0.33333333,  0.33333333, -0.83333333, -0.16666667,
        0.66666667])

In [1]:
L_rw([1,:])

SyntaxError: invalid syntax (<ipython-input-1-946580076772>, line 1)