In [58]:
import numpy as np
import sympy as sym
import scipy as sci
import matplotlib as mpl
import random
import math
#引入几个常用的库
#使用np.array 要查证好。


"""
忘记矩阵这个东西，你将获取python numpy所有的功能，所以matrix一律用array取代。
"""

In [59]:
DegreeM = np.array([[2,0,0,0,0,0],
                    [0,3,0,0,0,0],
                    [0,0,2,0,0,0],
                    [0,0,0,3,0,0],
                    [0,0,0,0,3,0],
                    [0,0,0,0,0,1],
    
],dtype=np.float64)
#度矩阵

In [60]:
AdjM   =  np.array([[0,1,0,0,1,0],
                    [1,0,1,0,1,0],
                    [0,1,0,1,0,0],
                    [0,0,1,0,1,1],
                    [1,1,0,1,0,0],
                    [0,0,0,1,0,0],
    
],dtype=np.float64)
#连接矩阵

In [61]:
invDegreeM =np.linalg.inv(DegreeM)
#度矩阵求逆运算

In [62]:
invDegreeM

array([[0.5       , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.33333333, 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.5       , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.33333333, 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.33333333,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        1.        ]])

In [63]:
invDegreeM*DegreeM #这是对应的元素乘法

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [64]:
LaplaOR = DegreeM - AdjM 

In [65]:
LaplaOR #普通形式的laplacian

array([[ 2., -1.,  0.,  0., -1.,  0.],
       [-1.,  3., -1.,  0., -1.,  0.],
       [ 0., -1.,  2., -1.,  0.,  0.],
       [ 0.,  0., -1.,  3., -1., -1.],
       [-1., -1.,  0., -1.,  3.,  0.],
       [ 0.,  0.,  0., -1.,  0.,  1.]])

In [66]:
LaplaRW =  np.matmul(invDegreeM , LaplaOR)#这是真正的矩阵乘法 ，随机行走矩阵

In [67]:
LaplaRW

array([[ 1.        , -0.5       ,  0.        ,  0.        , -0.5       ,
         0.        ],
       [-0.33333333,  1.        , -0.33333333,  0.        , -0.33333333,
         0.        ],
       [ 0.        , -0.5       ,  1.        , -0.5       ,  0.        ,
         0.        ],
       [ 0.        ,  0.        , -0.33333333,  1.        , -0.33333333,
        -0.33333333],
       [-0.33333333, -0.33333333,  0.        , -0.33333333,  1.        ,
         0.        ],
       [ 0.        ,  0.        ,  0.        , -1.        ,  0.        ,
         1.        ]])

In [68]:
MatrixLaplaRW = np.matrix(LaplaRW)

In [69]:
#至今没有找到随机行走形式的拉普拉斯矩阵变为随机矩阵的方法。
#但是知乎上有了第二个定义，这个定义就很好了。
#https://www.zhihu.com/question/54504471

In [70]:
#Dim_AdjM = AdjM.ndim 错误了
#Dim_AdjM = AdjM.size 也错了
Dim_AdjM = AdjM.shape
Zh_LaplaRW = np.identity(Dim_AdjM[0]) - np.matmul(invDegreeM , AdjM)#知乎上定义的随机行走矩阵

In [71]:
Dim_AdjM[0]

6

In [72]:
Zh_LaplaRW

array([[ 1.        , -0.5       ,  0.        ,  0.        , -0.5       ,
         0.        ],
       [-0.33333333,  1.        , -0.33333333,  0.        , -0.33333333,
         0.        ],
       [ 0.        , -0.5       ,  1.        , -0.5       ,  0.        ,
         0.        ],
       [ 0.        ,  0.        , -0.33333333,  1.        , -0.33333333,
        -0.33333333],
       [-0.33333333, -0.33333333,  0.        , -0.33333333,  1.        ,
         0.        ],
       [ 0.        ,  0.        ,  0.        , -1.        ,  0.        ,
         1.        ]])

In [74]:
#import math
#SqrIn_DegreeM = math.pow(DegreeM,-0.5) 错误

TypeError: only size-1 arrays can be converted to Python scalars

In [77]:
import numpy as np
from numpy import linalg as la

v, Q = la.eig(DegreeM)
print(v)
V = np.diag(v**(-0.5))
print(V)
T = Q*V*la.inv(Q)
#print(T)

[2. 3. 2. 3. 3. 1.]
[[0.70710678 0.         0.         0.         0.         0.        ]
 [0.         0.57735027 0.         0.         0.         0.        ]
 [0.         0.         0.70710678 0.         0.         0.        ]
 [0.         0.         0.         0.57735027 0.         0.        ]
 [0.         0.         0.         0.         0.57735027 0.        ]
 [0.         0.         0.         0.         0.         1.        ]]


In [78]:
print(T)

[[0.70710678 0.         0.         0.         0.         0.        ]
 [0.         0.57735027 0.         0.         0.         0.        ]
 [0.         0.         0.70710678 0.         0.         0.        ]
 [0.         0.         0.         0.57735027 0.         0.        ]
 [0.         0.         0.         0.         0.57735027 0.        ]
 [0.         0.         0.         0.         0.         1.        ]]


In [79]:
TAdjM = np.matmul(T, AdjM)

In [80]:
TAdjMT = np.matmul(TAdjM , T)

In [81]:
TAdjMT

array([[0.        , 0.40824829, 0.        , 0.        , 0.40824829,
        0.        ],
       [0.40824829, 0.        , 0.40824829, 0.        , 0.33333333,
        0.        ],
       [0.        , 0.40824829, 0.        , 0.40824829, 0.        ,
        0.        ],
       [0.        , 0.        , 0.40824829, 0.        , 0.33333333,
        0.57735027],
       [0.40824829, 0.33333333, 0.        , 0.33333333, 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.57735027, 0.        ,
        0.        ]])